### ISSUE TITLE
Trial?

### ISSUE THREAD

**Issue by CJSharkie** [Auction-Sniper/ShopGoodwill#1]
Is there a trial version of this software? Trying to use it but it is asking for 99.99. I would at least want to make sure it works before trying it.

**Comment by Auction-Sniper** [comment]
Hi CJSharkie, 

We offer a trial of 1 snipe free to test out the program and it's functionalities, furthermore, the $99 version if the version that contains both the ebay.com sniper and the shopgoodwill.com sniper so that is double the price of the standalone version basically, you can just by the standalone sniper for shopgoodwill too for half price only $49, you can download SGW here:

[http://SGWSniper.com](http://SGWSniper.com)
